map_type:             costmap
obstacle_range:       2.5
raytrace_range:       3.0
transform_tolerance:  0.2

robot_radius:        0.009
inflation_radius:     0.001
observation_sources:  laser_scan_sensor
laser_scan_sensor: {sensor_frame: prototype_lidar_link, data_type: LaserScan,topic: /scan,marking: true, clearing: true}
