map_type:             costmap
obstacle_range:       2.5
raytrace_range:       3.0
transform_tolerance:  0.2

robot_radius:        1
inflation_radius:     0.1
observation_sources:  laser_scan_sensor
laser_scan_sensor: {sensor_frame: center_laser_link, data_type: LaserScan,topic: /prototype_one/laser/scan, marking: true, clearing: true}
