 local_costmap:
  global_frame: map
  meter_scoring: true
  robot_base_frame: prototype_two_base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05
